application: esoteric-sled
version: 1
runtime: go
api_version: go1

handlers:

- url: /$
  static_files: site/index.html
  upload: site/index.html

- url: /
  static_dir: site

- url: /.*
  script: _go_app
